 
version: '3'
services:
  app: 
    build: "./app"
    container_name: "node-app"
    restart: "always"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    container_name: "mongo"
    restart: "always"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=matin321Q"
    ports:
      - "8000:27017"